name: fidnet
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.12
  - pip
  - numpy==1.23.4
  - cudatoolkit
  - tensorflow-gpu
  - matplotlib
  - pip:
      - -e .
      - nmrglue
      - keras == 2.6
